export const certificates = [
  {
    id: 1,
    title: 'Fundamentals of Digital Marketing',
    issuer: 'Google',
    date: '2025',
    description: 'Comprehensive training in digital marketing concepts, strategies, and tools.',
    image: '/images/certificates/digital-marketing.jpg',
  },
  {
    id: 2,
    title: 'Artificial Intelligence (AI) for Social Impact',
    issuer: 'ADBInstitute',
    date: '2025',
    description: 'Exploring the potential of AI to address social challenges and drive positive change.',
    image: '/images/certificates/ai-social-impact.jpg',
  },

  {
    id: 4,
    title: 'Cloud Computing Webinar',
    issuer: 'SysCare IT Solutions',
    date: '2025',
    description: 'Insights into cloud computing technologies, architecture, and industry trends.',
    image: '/images/certificates/cloud-computing.jpg',
  },
  {
    id: 5,
    title: 'Cybersecurity Webinar',
    issuer: 'SysCare IT Solutions',
    date: '2025',
    description: 'Overview of cybersecurity threats, best practices, and defense strategies.',
    image: '/images/certificates/cybersecurity.jpg',
  },
  {
    id: 6,
    title: 'Introduction to E-commerce',
    issuer: 'ADBInstitute',
    date: '2025',
    description: 'Fundamental concepts of electronic commerce, business models, and digital trade.',
    image: '/images/certificates/ecommerce-intro.jpg',
  },
  {
    id: 7,
    title: 'Introduction to JIRA',
    issuer: 'Simplilearn',
    date: '2025',
    description: 'Guide to using JIRA for project management, issue tracking, and agile workflows.',
    image: '/images/certificates/jira-intro.jpg',
  },
  {
    id: 8,
    title: 'Power BI for Beginners',
    issuer: 'Simplilearn',
    date: '2025',
    description: 'Introduction to data visualization and business intelligence using Microsoft Power BI.',
    image: '/images/certificates/power-bi.jpg',
  },
  {
    id: 9,
    title: 'Prompt Engineering',
    issuer: 'Aeturnum',
    date: '2023',
    description: 'The art of crafting effective prompts to guide AI models and optimize outputs.',
    image: '/images/certificates/prompt-engineering.jpg',
  },
];

export const academicProjects = [
  {
    id: 1,
    title: 'TerraFlow',
    description: 'Full-stack supply chain management system for clay product manufacturing businesses. Features end-to-end operations management, smart production recommendations powered by real-time data, inventory tracking, and secure Stripe payment integration.',
    techStack: ['React.js', 'Node.js', 'PHP', 'MySQL', 'Stripe'],
    github: 'https://github.com/username/terraflow',
    demo: 'https://terraflow.com',
    image: '/images/terraflow.jpg',
  },
  {
    id: 2,
    title: 'StayFinder',
    description: 'A web-based application designed to make finding and reserving boarding accommodations easier for university students. Features user registration, advanced search, reviews, and automated notifications.',
    techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'MySQL'],
    github: 'https://github.com/disalrajapaksha/stayfinder',
    demo: 'https://stayfinder.com',
    image: '/images/stayfinder.jpg',
  },
  {
    id: 3,
    title: 'E-Commerce Platform',
    description: 'Full-featured online shopping platform with payment integration, inventory management, and user authentication.',
    techStack: ['React', 'Node.js', 'MongoDB', 'Stripe'],
    github: 'https://github.com/username/ecommerce-platform',
    demo: 'https://demo-ecommerce.com',
  },
  {
    id: 4,
    title: 'Student Management System',
    description: 'Comprehensive system for managing student records, attendance, grades, and course enrollment.',
    techStack: ['Next.js', 'PostgreSQL', 'Prisma', 'TypeScript'],
    github: 'https://github.com/username/student-management',
    demo: 'https://demo-sms.com',
  },
  {
    id: 5,
    title: 'IoT Smart Home Dashboard',
    description: 'Real-time monitoring and control interface for IoT devices with data visualization and automation rules.',
    techStack: ['React', 'Firebase', 'MQTT', 'Chart.js'],
    github: 'https://github.com/username/smart-home',
    demo: 'https://demo-smarthome.com',
  },
];

export const personalProjects = [
  {
    id: 1,
    title: 'Task Management App',
    description: 'Intuitive productivity tool with task tracking, project organization, and team collaboration features.',
    techStack: ['Vue.js', 'Express', 'MySQL', 'Socket.io'],
    github: 'https://github.com/username/task-manager',
    demo: 'https://demo-tasks.com',
  },
  {
    id: 2,
    title: 'Weather Forecast Application',
    description: 'Real-time weather information with 7-day forecasts, location-based alerts, and interactive maps.',
    techStack: ['React Native', 'OpenWeather API', 'Redux'],
    github: 'https://github.com/username/weather-app',
    demo: 'https://demo-weather.com',
  },
  {
    id: 3,
    title: 'Recipe Sharing Platform',
    description: 'Social platform for sharing recipes with ingredient lists, cooking instructions, and user ratings.',
    techStack: ['Angular', 'Firebase', 'Tailwind CSS'],
    github: 'https://github.com/username/recipe-platform',
    demo: 'https://demo-recipes.com',
  },
  {
    id: 4,
    title: 'Portfolio Builder',
    description: 'No-code tool for creating professional portfolios with customizable templates and drag-and-drop interface.',
    techStack: ['Next.js', 'Supabase', 'Framer Motion'],
    github: 'https://github.com/username/portfolio-builder',
    demo: 'https://demo-portfolio.com',
  },
  {
    id: 5,
    title: 'Supermarket POS',
    description: 'A comprehensive Point of Sale system for supermarkets, featuring inventory management, sales tracking, and reporting.',
    techStack: ['Node.js', 'Express', 'MySQL', 'HTML', 'CSS', 'JavaScript'],
    github: '#',
    demo: '#',
    image: '/supermarket-pos.png',
  },
];
